export const HTTP_STATUS_UNAUTHORIZED = 401;
export const HTTP_STATUS_CONFLICT = 409;
export const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;
export const INTERNAL_SERVER_ERROR = 'На сервере произошла ошибка.';
export const MOVIES_API_URL = 'https://api.nomoreparties.co';
export const SHORT_MOVIE_DURATION = 40;
export const DEBOUNCE_TIME_MS = 500;
export const DESKTOP_INIT_CARDS = 12;
export const TABLET_INIT_CARDS = 8;
export const MOBILE_INIT_CARDS = 5;
export const DESKTOP_MORE_CARDS = 3;
export const TABLET_MORE_CARDS = 2;
export const MOBILE_MORE_CARDS = 2;
export const DESKTOP_RESOLUTION = 972;
export const TABLET_RESOLUTION = 636;
export const MOBILE_RESOLUTION = 635;
export const EMAIL_REGEX = /^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/